linuxamd64_task:
  container:
    image: amd64/centos:7
  env:
    matrix:
      - GOVERSION: 1.12
      - GOVERSION: 1.13
      - GOVERSION: 1.14
  test_script:
    -  yum -y install wget make git gcc
    -  wget -q https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz
    -  tar -C /usr/local -xzf go${GOVERSION}.linux-amd64.tar.gz
    -  cd /usr/local/go/src
    -  ./all.bash
    #    -  export PATH=$PATH:/usr/local/go/bin
    #    -  uname -a

linux386_task:
  container:
    image: i386/centos:7
  env:
    matrix:
      - GOVERSION: 1.12
      - GOVERSION: 1.13
      - GOVERSION: 1.14
  test_script:
    -  yum -y update && yum -y upgrade
    -  yum -y install wget make git gcc
    -  wget -q https://dl.google.com/go/go${GOVERSION}.linux-386.tar.gz
    -  tar -C /usr/local -xzf go${GOVERSION}.linux-386.tar.gz
    -  uname -a
    -  cd /usr/local/go/src
    -  ./all.bash
    #-  export PATH=$PATH:/usr/local/go/bin
    #-  go version
